version: '2'

services:
  db:
    container_name: freechat-db
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: snowy
      POSTGRES_PASSWORD: p2qH43iS5wkdjTpyi9SoVkbtk4Z5BwR
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/var/lib/postgres/data
  redis:
    container_name: freechat-redis
    image: redis:3.2-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
  pgadmin:
    container_name: freechat-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: code@juul.xyz
      PGADMIN_DEFAULT_PASSWORD: I0YMSbiGoRccR2mL7Xut2fkLCtVqJzgM
    ports:
      - 5430:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
